-- Fase 2. Ejecutar completo en SQL Editor del proyecto que ya contiene el login.
-- Ejecutar una sola vez. Si las tablas ya existen, detenerse y revisar.
begin;

create table public.inventory_members (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique check (btrim(name) <> ''),
  created_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  sku text not null unique check (btrim(sku) <> ''),
  name text not null check (btrim(name) <> ''),
  category_id bigint not null references public.categories(id),
  brand text not null default '',
  model text not null default '',
  characteristics text not null default '',
  stock integer not null default 0 check (stock >= 0),
  price numeric(12, 2) not null check (price >= 0 and price <> 'NaN'::numeric),
  min_stock integer not null default 5 check (min_stock >= 0),
  source_status text not null default '',
  created_at timestamptz not null default now()
);

create index products_category_id_idx on public.products(category_id);

alter table public.inventory_members enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;

-- En esta fase solo se prepara la lectura. Las escrituras y el historial
-- se habilitarán juntos en la fase de conexión de la aplicación.
revoke all on table public.inventory_members, public.categories, public.products
  from public, anon, authenticated;
revoke all on sequence public.categories_id_seq, public.products_id_seq
  from public, anon, authenticated;
grant select on table public.inventory_members, public.categories, public.products
  to authenticated;

create policy inventory_members_read_self
  on public.inventory_members for select to authenticated
  using (user_id = (select auth.uid()));

create policy categories_read_members
  on public.categories for select to authenticated
  using (exists (
    select 1 from public.inventory_members m
    where m.user_id = (select auth.uid())
  ));

create policy products_read_members
  on public.products for select to authenticated
  using (exists (
    select 1 from public.inventory_members m
    where m.user_id = (select auth.uid())
  ));

commit;

-- Deben aparecer las tres tablas con rowsecurity = true.
select tablename, rowsecurity
from pg_tables
where schemaname = 'public'
  and tablename in ('categories', 'products', 'inventory_members')
order by tablename;
