-- Pendiente: incorporar las definiciones reales de tablas del proyecto Supabase.
-- Este archivo organiza la estructura solicitada y no ejecuta cambios.
-- No reconstruir el esquema de producción a partir del código cliente.
